.DEFAULT_GOAL = help

create_petalog: 
	flutter create \
		-t app \
		--platforms android,ios \
		--org jp.allflavor \
		-a kotlin \
		-i swift \
		--description "petalog" \
		./petalog

create_common:
	flutter create \
		-t package \
		--org jp.allflavor \
		-a kotlin \
		-i swift \
		--description "common" \
		./common

help:
	@echo "help"